### ISSUE TITLE
Support for jsonpb

### ISSUE THREAD

**Issue by sjezewski** [ghodss/yaml#17]
Hi there! 

We have a use case where we have configuration backed by protocol buffer definitions. Today, we use jsonpb to marshal/unmarshal as the std library's json en/decoder doesn't play nice with protocol buffers.

Can your library add support for the jsonpb codec? We'd love to be able to support yaml files for our users

**Comment by ghodss** [comment]
I believe it probably makes sense for this library to remain exclusively about YAML, given its name and to prevent bloating. But another library that also read off the same JSON tags (instead of dedicated jsonpb tags, for example) would probably get you the result you're looking for.
